version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "ROOT"
      MONGO_INITDB_ROOT_PASSWORD: "Gutz333;Lps32;Jv18@mongo"
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-data:/data/db"

  app: 
    build: .
    container_name: social_post_ai_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: pnpm dev
    depends_on:
      - mongodb

volumes:
  social_post_ai_mongo_data:
